spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/quant_data
    # username: postgres
    # password: 1235679@
    username: xiaoxiao_coder
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
server:
  port: 8080
  timezone: Asia/Hong_Kong # 設置服務器時區
jwt:
  secret: your_jwt_secret_key_1234567890abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890
  expiration: 86400000
okx:
  api-url: "https://www.okx.com"
  ws-url: "wss://ws.okx.com:8443/ws/v5/public"
logging:
  level:
    root: INFO
    com.example.crypto: INFO
proxy:
  enabled: true
  type: http # http 或 socks
  host: 127.0.0.1
  port: 9098
  ws-type: socks
  ws-port: 19250
binance:
  api-url: https://api.binance.com
  ws-url: wss://stream.binance.com:9443/ws

fcsapi:
  access-key: "kFvQIk29CmU2deg8barnc9EE"
  base-url: "https://fcsapi.com/api-v3/forex/history"
  sync-on-startup: false # true: 启动时同步, false: 启动时不同步

backtest:
  python:
    # For local macOS development, ensure 'python3' points to a valid interpreter.
    # For production CentOS deployment, this should point to the compiled Python path.
    executable: /Users/xiaoxiao_coder/Desktop/quant_project/backtest/maxquant_backtest/venv/bin/python
    # Add the path to the runner script, relative to the project root.
    runner-script-path: /Users/xiaoxiao_coder/Desktop/quant_project/backtest/maxquant_backtest/launcher_new.py
    # executable: /Users/xiaoxiao_coder/Desktop/quant_project/quantlib/venv/bin/python3
  # executable: python3
clickhouse:
  datasource:
    url: jdbc:clickhouse://localhost:8123/default
    username: default
    password: ""
    driver-class-name: com.clickhouse.jdbc.ClickHouseDriver



