spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/quant_data
    username: xiaoxiao_coder
    password: 
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
server:
  port: 8080
  timezone: Asia/Hong_Kong # 設置服務器時區
jwt:
  secret: your_jwt_secret_key_1234567890abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890
  expiration: 86400000
okx:
  api-url: "https://www.okx.com"
  ws-url: "wss://ws.okx.com:8443/ws/v5/public"
logging:
  level:
    root: INFO
    com.example.crypto: INFO
